### ISSUE TITLE
Python3 support broken with last commit

### ISSUE THREAD

**Issue by budbach** [foxpass/foxpass-radius-agent#18]
Upgraded to the latest version and https://github.com/foxpass/foxpass-radius-agent/commit/afcb86e4e7d04600637d60885faf2c9cd79079ca seems to break py3 support:

```
May 11 10:52:53 radius-proxy2 systemd[1]: Started Foxpass RADIUS agent.
May 11 10:52:54 radius-proxy2 python3[1681]: 2020-05-11 10:52:54,189 INFO     Listening on port 0.0.0.0:1812
May 11 11:56:54 radius-proxy2 python3[1681]: 2020-05-11 11:56:54,756 INFO     received 109 bytes from ('172.16.11.254', 39871)
May 11 11:56:54 radius-proxy2 python3[1681]: Traceback (most recent call last):
May 11 11:56:54 radius-proxy2 python3[1681]:   File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
May 11 11:56:54 radius-proxy2 python3[1681]:   File "/usr/local/lib/python3.7/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
May 11 11:56:54 radius-proxy2 python3[1681]:     return handle(*args_tuple)
May 11 11:56:54 radius-proxy2 python3[1681]:   File "/usr/local/bin/foxpass-radius-agent.py", line 323, in handle
May 11 11:56:54 radius-proxy2 python3[1681]:     response_data = process_request(data, address, self.secret)
May 11 11:56:54 radius-proxy2 python3[1681]:   File "/usr/local/bin/foxpass-radius-agent.py", line 272, in process_request
May 11 11:56:54 radius-proxy2 python3[1681]:     dict=Dictionary(io.BytesIO(DICTIONARY_DATA)))
May 11 11:56:54 radius-proxy2 python3[1681]: TypeError: a bytes-like object is required, not 'str'
May 11 11:56:54 radius-proxy2 python3[1681]: 2020-05-11T16:56:54Z <Greenlet at 0xb59be810: _handle_and_close_when_done(<bound method RADIUSServer.handle of <RAD
```

Reverted to https://github.com/foxpass/foxpass-radius-agent/commit/547f1447d1d8c35fac39617bf294a00f1d13ac40 and things seem fine.

**Comment by aren** [comment]
Sorry about that. I believe I've fixed it in the `py3_fix` brach. Can you confirm it works for you?

**Comment by budbach** [comment]
Tested and works under py3.  Thanks!

**Comment by aren** [comment]
Thanks. PR created, pending internal review.
